locales:
  en:
    name: English Keyboards
    description: >-
      Mobile OS keyboards for the English language from the Divvun group
      at UiT.
  en:
    name: English Keyboards
    description: >-
      Mobile OS keyboards for the English language from the Divvun group
      at UiT.
  nb:
    name: English tastatur
    description: Mobiltastatur for English fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
